### ISSUE TITLE
Support jinja 3.x

### ISSUE THREAD

**Issue by benbariteau** [unmade/thrift-pyi#36]
Currently, if you install thrift-pyi, it will install `jinja2` at `^2.10` and the latest `MarkupSafe`, which are mutually incompatible. Obviously, this can be fixed by pinning back MarkupSafe to an older version which is compatible, but `jinja2` 2.x is considered unsupported (see https://github.com/pallets/jinja/issues/1585 for more details). The error that I see looks like this:
```
$ venv/bin/thriftpyi 
Traceback (most recent call last):
  File "/home/breetz/foo/venv/bin/thriftpyi", line 5, in <module>
    from thriftpyi.cli import main
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/thriftpyi/cli.py", line 3, in <module>
    from thriftpyi.main import thriftpyi
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/thriftpyi/main.py", line 5, in <module>
    from thriftpyi import factories, files, renderers
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/thriftpyi/renderers.py", line 4, in <module>
    from jinja2 import Template
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/breetz/foo/venv/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/breetz/foo/venv/lib/python3.10/site-packages/markupsafe/__init__.py)
```

This can be solved by supporting `jinja2` 3.x, which fixes this error.

**Comment by unmade** [comment]
Hey, @benbariteau 

Thanks for reporting this issue. I will take a look at the problem and try to fix it in the next couple days.

**Comment by unmade** [comment]
I remove Jinja dependecy, feel free to upgrade to `v0.4.0`
